repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.277"
    hooks:
      - id: ruff
        # Autofix, and respect `exclude` and `extend-exclude` settings.
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/ambv/black
    rev: 22.11.0
    hooks:
      - id: black
        language_version: python3
