name: Client Unit tests
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
    secrets:
      MODAL_TOKEN_ID:
        required: true
      MODAL_TOKEN_SECRET:
        required: true

env:
  UV_FROZEN: 1
  TERM: linux
  TERMINFO: /etc/terminfo
  PYTHONIOENCODING: utf-8

jobs:
  client-test:
    name:
      Unit tests on ${{ matrix.python-version }} and ${{ matrix.os }}
      (protobuf=${{ matrix.proto-version }})
    timeout-minutes: 30

    strategy:
      fail-fast: false # run all variants across python versions/os to completion
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: ["ubuntu-24.04"]
        proto-version: ["latest"]
        include:
          - os: "macos-15-intel" # x86-64
            python-version: "3.10"
            proto-version: "latest"
          - os: "macos-15" # ARM64 (M1)
            python-version: "3.10"
            proto-version: "latest"
          - os: "windows-latest"
            python-version: "3.10"
            proto-version: "latest"
          - os: "ubuntu-24.04"
            python-version: "3.10"
            proto-version: "3.20"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: ./.github/actions/setup-cached-python-client
        with:
          version: ${{ matrix.python-version }}
          working-directory: ${{ inputs.working-directory }}
          no-build-isolation:
            ${{ matrix.os == 'macos-15' && 'true' || 'false' }}

      - name: Build client package (installs all dependencies)
        run: uv pip install -e .

      - if: matrix.proto-version != 'latest'
        name: Install specific protobuf version (override lock file)
        run: uv pip install protobuf==${{ matrix.proto-version }}

      - name: Build protobuf
        run: inv protoc

      - name: Run client tests
        run: inv test

      - name: Run docstring tests
        if: github.event.pull_request.head.repo.fork == false
        env:
          MODAL_ENVIRONMENT: client-doc-tests
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
        run: pytest -v --markdown-docs -m markdown-docs modal

  container-dependencies:
    name:
      Check minimal container dependencies for ${{ matrix.python-version }} -
      ${{ matrix.image-builder-version }}
    runs-on: ubuntu-24.04
    timeout-minutes: 4
    strategy:
      matrix:
        include:
          - image-builder-version: "2024.04"
            python-version: "3.10"
          - image-builder-version: "2024.04"
            python-version: "3.12"
          - image-builder-version: "2024.10"
            python-version: "3.10"
          - image-builder-version: "2024.10"
            python-version: "3.13"
          - image-builder-version: "2025.06"
            python-version: "3.10"
          - image-builder-version: "2025.06"
            python-version: "3.14"

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r modal/builder/${{ matrix.image-builder-version }}.txt
          pip install synchronicity

      - name: Compile protos
        run:
          .github/scripts/client-generate-container-runtime-protos.sh ${{
          inputs.working-directory }} ${{ matrix.python-version }}
        working-directory: "."

      - name: Check entrypoint import
        run: |
          python -c 'import modal._container_entrypoint; import modal._runtime.asgi'
          if [ "${{ matrix.image-builder-version }}" == "2024.04" ]; then python -c 'import fastapi'; fi
